server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: 12345678
    url: jdbc:postgresql://localhost:5432/thymeleafdemo
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  server:
    servlet:
      session:
        timeout : 1800
