server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    session:
      timeout: 450 # Set the session timeout to 3600 seconds (60 minutes)

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: schoolmanagement05.12@gmail.com
    password: hioi wtwj nsnd vico
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    password: 2gCDGdgeec*f5d*geDgffeaF*Cc534f2
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:53917/railway
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 5
          order_inserts: true
          order_update: true
          order_delete: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 710177561209-f48e675l83eh471c1o0ifnaussttmv99.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    cache-names: genderCache, ethnicCache,religionCache, roleCache, cityCache, districtCache, wardCache
    ehcache:
      config: classpath:ehcacheConfig.xml
logging:
  level:
    org:
      springframework:
        security: Trace
        data:
          jpa: debug
